// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/acongos92/andyauth/models"
)

// VerifyNoContentCode is the HTTP code returned for type VerifyNoContent
const VerifyNoContentCode int = 204

/*VerifyNoContent valid token

swagger:response verifyNoContent
*/
type VerifyNoContent struct {
}

// NewVerifyNoContent creates VerifyNoContent with default headers values
func NewVerifyNoContent() *VerifyNoContent {

	return &VerifyNoContent{}
}

// WriteResponse to the client
func (o *VerifyNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// VerifyForbiddenCode is the HTTP code returned for type VerifyForbidden
const VerifyForbiddenCode int = 403

/*VerifyForbidden token was not valid

swagger:response verifyForbidden
*/
type VerifyForbidden struct {
}

// NewVerifyForbidden creates VerifyForbidden with default headers values
func NewVerifyForbidden() *VerifyForbidden {

	return &VerifyForbidden{}
}

// WriteResponse to the client
func (o *VerifyForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// VerifyInternalServerErrorCode is the HTTP code returned for type VerifyInternalServerError
const VerifyInternalServerErrorCode int = 500

/*VerifyInternalServerError internal server error

swagger:response verifyInternalServerError
*/
type VerifyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewVerifyInternalServerError creates VerifyInternalServerError with default headers values
func NewVerifyInternalServerError() *VerifyInternalServerError {

	return &VerifyInternalServerError{}
}

// WithPayload adds the payload to the verify internal server error response
func (o *VerifyInternalServerError) WithPayload(payload *models.Error) *VerifyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the verify internal server error response
func (o *VerifyInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *VerifyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
