// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Performs simple authentication
Authentication Api


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /vcongos/andyauth/1.0.0
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
